### ISSUE TITLE
Logging out is unreliable

### ISSUE THREAD

**Issue by rasmusohrstig** [telenordigital/connect-android-sdk#119]
If we call ConnectSdk.logout() we expect to get a confirmation that we have logged out. This happens, but the problem is that it happens even when the network request to the revoke endpoint fails. 

We can recreate this error in our app by enabling airplane mode before clicking the logout button. It is probably possible to recreate it in the same way in the example project, but I have not tried that yet.

Based on the code it looks like it would be fairly straightforward to fix the bug by removing the call to clearTokensAndNotify() from ConnectIdService.revokeTokens() and adding appropriate implementations of success(Response response) and failure(RetrofitError error) in the ResponseCallback used in ConnectIdService.revokeToken()

The current implementation of failure(RetrofitError error) also logs the still valid token to logcat, if I'm reading the code correctly, which seems like a minor security flaw.

**Comment by rasmusohrstig** [comment]
So just to clarify: the root cause of the bug is that the SDK ignores the result of the network request to "/oauth/revoke".

**Comment by jorunfa** [comment]
See your point, and if I can remember correctly, we had a (security) discussion before agreeing on this implementation. I think the gist of it was that oauth/openid connect allows for best effort logging out/revoking of tokens, and that the user experience would suffer if, for an example, the user could not log out when you have a spotty mobile connection or on a plane. We were not absolutely sure it was the better call when we made it.

Is there a specific reason why you need a callback, which could help in reevaluating?

The logging is not intentional, will have a look at that.

**Comment by rasmusohrstig** [comment]
Well, this came up during testing. The refresh token stored in Chrome will still be valid, which means you can just re-open the app, click the login button, get logged in automatically and continue using the app.

I think this is a security issue for a user who is using an app on a shared device that supports Chrome custom tabs.

I don't think it's possible to tell Chrome or the Chrome custom tab to delete the cookies, so there does not seem to be a workaround that will fully wipe the still valid tokens from the device.

From a developer's point of view I think it would be useful to get more fine-grained callbacks, at least when using Chrome custom tabs.

**Comment by jorunfa** [comment]
See your point - I think we can add that. Not sure how soon we can prioritise this one, but it shouldn't be very hard, as you mentioned.

**Comment by jorunfa** [comment]
I started looking at this, but I think I would like to challenge you on how you would like this to work - what kind of interface would you like and what expectations do you have.

There are a few network calls which all can fail, in `ConnectIdService.java`:
1. `updateTokens` (should maybe be `getValidAccessToken` instead, to be fair).
1. `callLogOutApiEndpoint`
1. `revokeAccessToken`
1. `revokeRefreshToken`

And we also call
```
clearTokensAndNotify();
clearCookies(context);
```
To clear the tokens from the store and any WebView cookies.

Say network request 1, 2, and 4 succeed, but the third one does not - let's say from connectivity issues.

Would you then expect to get a callback letting you know that that one failed so you could make that call manually, or expect to be able to call the same method again and have it clear out "the rest", whatever that may be in the circumstance. One problem with both is that the users signed in state is in a sort of limbo, where the user has an access token, but no way of refreshing his tokens because that was revoked, and also no browser SSO, so it's a bit of an inconsistent state. Also, should we call `clearTokensAndNotify` when 1 out of 2 tokens are valid? And of course there are many other combinations here.

So I'm not sure what to do here - part of me feels best effort is good enough, and from what I can remember I think that is allowed by the standard(s). Feedback would be welcome. If you have a suggestion, I would be happy to do a review of a pull request.

**Comment by rasmusohrstig** [comment]
I think the important thing is to be able to give the end user feedback on what's happened. I think we want the messages to err on the side of being pessimistic, so that the user does not get a false sense of security.

I think there are two or three potential messages that we could want to send to the user in various situations: 

When fully logged out:
"Logged out"

When not logged out, or partially logged out:
"Logging out failed. Try again later."

When not logged out, but SSO logged out:
"Logging out failed. Your single sign on session did log out, but you are still logged in in the app. Try again later."

The "Logging out failed. Try again later." message would cover most of the partially logged out / in limbo states.

Here is how I imagine it could work:

Callbacks:
onSsoLoggedOut
onLoggedOut
onLogOutFailed

0. Update tokens if necessary
On success: continue
On failure: send callback onLogOutFailed, quit

1. Log out SSO
On success: send callback onSsoLoggedOut, continue
On failure: send callback onLogOutFailed, quit

2. Revoke access token
On failure: send callback onLogOutFailed, quit

4. Delete locally stored access token

5. Revoke refresh token
On success: continue
On failure: send callback onLogOutFailed, quit

6. Delete locally stored refresh token

7. Send callback onLoggedOut

**Comment by rasmusohrstig** [comment]
I'm not sure how we would recover from the onLogOutFailed states. The user would want to click the log out button again and have the SDK do whatever is needed to log out.

Maybe we also need an alreadyLoggedOut callback in case the user was already logged out.

**Comment by jorunfa** [comment]
There is at least the case where the revoke access token request reaches the server and is revoked, but the reply does not come back (i.e. intermittent network failure). Then the user/sdk might believe they still have access (still has the access token that isn't expired), but doesn't really - `getValidAccessToken()` would still give the same token, even though it was revoked.

This might be the best course of action, but it does mean that the SDK would probably need more logic to handle states it wasn't originally engineered to handle, i.e. having/missing access/refresh token, and these being valid/not valid -> 2^3 = 8, where it originally just had/didn't have valid tokens. So the biggest problem probably isn't trying again, but the SDK/app handling a state where the user is  is partially logged out, but not fully. _Schrödingers signed in_ (in and out at the same time, until we have made a new request).

This would require a bit of work, and I can't currently devote the amount of time it would require, without further proof that this is a significant/worthwhile problem (users logging out with network problems, given a bad user experience noticing that SSO/token was not invalidated), rather than a nice to have.

Hope I have been able to successfully communicate the challenge. I would be able to change my mind should any new evidence be presented, showing that it is a bigger problem than first thought.
