### ISSUE TITLE
Chrome custom tab no longer works (most of the time)

### ISSUE THREAD

**Issue by rasmusohrstig** [telenordigital/connect-android-sdk#133]
Recently we seem to be falling back on the SDK:s built in web solution (ConnectActivity, WebView) on most devices almost all the time. We have seen this problem on Samsung Galaxy S7, S8 with Android 8 and Google Pixel 1 with Android 9.

I have tried to warm up the Chrome custom tab service and waiting before attaching the button to the layout, but it does not seem to help.

The if clause on line 80 in CustomTabsHelper seems to always be false. So in other words the PackageManager is not able to resolve the Intent.

**Comment by rasmusohrstig** [comment]
By they way, it would be a good idea to move the Intent resolution from View.onAttachedToWindow() to when the user presses the button. That would make it possible to warm up Chrome custom tabs before the Intent resolution code runs.

**Comment by simonnorberg** [comment]
We're using custom tabs from support library 28 with the new androidx package.
https://developer.android.com/jetpack/androidx/

`implementation "androidx.browser:browser:1.0.0"`

I think Gradle forces Connect SDK to use this version as well.

**Comment by jorunfa** [comment]
There is one known problem I've seen before:
![image](https://user-images.githubusercontent.com/1413275/46468380-8ac39a80-c7d0-11e8-8cd2-43ab773a9235.png)

The resolved activity for the intent is the ResolverActivity which, if I'm not mistaken, is the activity for choosing which app you want to open the intent in. This happens if you have multiple apps capable of opening the same uri. Do you have multiple apps using the same uri scheme installed on the device?

Can you debug this line and check? https://github.com/telenordigital/connect-android-sdk/blob/master/connect/src/com/telenor/connect/ui/ConnectLoginButton.java#L78

**Comment by jorunfa** [comment]
I see we're also using support library 27.something in the SDK. Can bump it to 28.

**Comment by jorunfa** [comment]
Can you try
```
$ git clone git@github.com:telenordigital/connect-android-sdk.git
$ cd connect-android-sdk/
$ git checkout custom-tabs
$ open -a /Applications/Android\ Studio.app .
(run id-example)
```
And see if that works? And if doing `$ git checkout master` or `git checkout v1.8.0` and running the example app isn't working?

**Comment by rasmusohrstig** [comment]
I tested your branch and it actually works. I also tried migrating to AndroidX in the same branch and it still works after that. So that's good.

I'm beginning to think that we have done something else in our app that has caused it to not work for us, becuase I tried checking out a version of our own app from a couple of weeks ago and that also worked.

I will keep looking for what it might be. I suspect it could be something to do with our Proguard setup.

**Comment by rasmusohrstig** [comment]
I have not yet tried using AndroidX in id-example while still using support in the library code.

That is basically what we are doing currently in our app.

**Comment by jorunfa** [comment]
Seems like a reasonable workaround. Thanks for doing the research!
Question:  Do we want to change this if we move from "normal" support lib -> androidx?

**Comment by soldierinwhite** [comment]
Yes, you would still need to change this. Since we would still enable jetifier in the client app to refactor other gradle libraries to androidx, the hardcoded string will still be changed. Of course, the workaround is unnecessary if Chrome and other browsers would update the action strings in their manifests, or jetifier would remove this bug/feature (it even refactors constant strings in the Android framework). 

Until then, the workaround seems like the quickest fix and would continue to work even if these fixes were to happen in the near future.

**Comment by jorunfa** [comment]
Merged and released. Does it work now/does this close the issue?
