### ISSUE TITLE
Missing lib download from gradle

### ISSUE THREAD

**Issue by infinityzero** [telenordigital/connect-android-sdk#37]
Is there any plan to add this lib in our project via gradle?

**Comment by jorunfa** [comment]
Hi.

Is the question if we're planning to make the Android Connect SDK addable as a dependency in Gradle?

The answer to that question is **yes**.

I am currently working to make the project accessible from a central repository, so that you can add the SDK by adding one or two lines to your Gradle script. I'll update the readme and let you know when that is available.



In the meantime you can add it to Gradle the following way
1. Download the project using git: (`git clone git@github.com:telenordigital/connect-android-sdk.git`)
2. Import the module to your project
![image](https://cloud.githubusercontent.com/assets/1413275/16760239/18d8f168-481b-11e6-8470-3647fa713ecc.png)
![image](https://cloud.githubusercontent.com/assets/1413275/16760321/6e4a3c2e-481b-11e6-8611-7b02b430005a.png)
![image](https://cloud.githubusercontent.com/assets/1413275/16760421/fba74c9c-481b-11e6-9cc9-6334aefa21af.png)
3. Add the project to your `build.gradle`:
```
compile project(path: ':connect')
```
![image](https://cloud.githubusercontent.com/assets/1413275/16760475/38423158-481c-11e6-8719-4f2d7933e60b.png)
4. You can then set the version of the Android Connect SDK using Git:
```bash
cd connect-android-sdk
git checkout v0.5.0
```

**Comment by infinityzero** [comment]
Yes, addable as a dependency in Gradle.

**Comment by jorunfa** [comment]
You can now add the Sdk by adding one line:
```gradle
dependencies {
    // ...
    compile 'com.telenor.connect:connect-android-sdk:0.5.0' // add this line
}
```

See the readme for more information. Future versions will also be published in this manner.
