### ISSUE TITLE
Bypass the allow dialog screen for existing users

### ISSUE THREAD

**Issue by infinityzero** [telenordigital/connect-android-sdk#40]
Can I bypass the allow dialog screen for existing users who are already allowed on first time login?

**Comment by jorunfa** [comment]
Hi! :)

Public clients will show the consent screen each time the user logs in. This is because of security reasons, to reduce the chance of successful phishing attacks.

However, the refresh token can be used to maintain long-time access, so the user should only have to log in once if the user does not actively log out. Let me know if you have any questions regarding this.

Another alternative is using confidential clients, but that requires a middleware server and a different setup.
